version: '2'
services:
  apiserver:
    image: gcr.io/google_containers/hyperkube-amd64:v1.9.0
    depends_on:
      - etcd
    ports:
      - 127.0.0.1:8080:8080
    command:
      - /hyperkube
      - apiserver
      - --insecure-bind-address=0.0.0.0
      - --external-hostname=apiserver
      - --bind-address=0.0.0.0
      - --secure-port=0
      - --etcd-servers=http://etcd:4001
      - --service-cluster-ip-range=10.254.0.1/24
      - --v=2
#  scheduler:
#    image: gcr.io/google_containers/hyperkube-amd64:v1.8.0
#    depends_on:
#      - apiserver
#    command:
#      - /hyperkube
#      - scheduler
#      - --master=apiserver:8080
#      - --v=2
#  controller-manager:
#    image: gcr.io/google_containers/hyperkube-amd64:v1.8.0
#    depends_on:
#      - apiserver
#    command:
#      - /hyperkube
#      - controller-manager
#      - --master=apiserver:8080
#      - --v=2
